name: release

on: 
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install npm deps
        run: npm install
      - name: Install npm dev
        run: npm install --only=dev
      - name: Create dist folder
        run: mkdir dist
      - name: Build Deb
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build
      - name: Set outputs
        id: vars
        run: echo "app_version=$(cat package.json| grep version | grep -Eo '[0-9\.]+' | head -1)" >> $GITHUB_OUTPUT
      - name: Use Go Action
        uses: softprops/action-gh-release@v2
        env:
          NODE_OPTIONS: '--experimental-fetch' # if nodejs < 18
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          name: GodotManager ${{ steps.vars.outputs.app_version }}
          tag_name: ${{ steps.vars.outputs.app_version }}
          files: |-
            builds/**/*.{deb,exe,AppImage,dmg,pkg}
